const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',

  GOOGLE_SIGIN_START: 'GOOGLE_SIGNIN_START',
  EMAIL_SIGIN_START: 'EMAIL_SIGNIN_START',

  SIGIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGIN_FAILURE: 'SIGNIN_FAILURE',
  
  CHECK_USER_SESSION: 'CHECK_USER_SESSION'
}

export default UserActionTypes;
