const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',

  GOOGLE_SIGIN_START: 'GOOGLE_SIGNIN_START',
  EMAIL_SIGIN_START: 'EMAIL_SIGNIN_START',

  SIGIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGIN_FAILURE: 'SIGNIN_FAILURE',
  
  // EMAIL_SIGIN_SUCCESS: 'EMAIL_SIGNIN_SUCCESS',
  // EMAIL_SIGIN_FAILURE: 'EMAIL_SIGNIN_FAILURE'
}

export default UserActionTypes;
